from django.urls import path
from .import views
urlpatterns = [
    path('', views.home),

    path('search', views.search),

    path('mjdboss', views.bossRegLogPage),
    path('bossReg', views.bossReg),
    path('bossLog', views.bossLog),
    path('boss/<int:bossID>',views.bossPage),
    path('boss/newProductPage/<int:bossID>',views.newProductPage),
    
    path('boss/add/product/<int:bossID>', views.addProduct),
    path('boss/product/detail/<int:productID>/<int:bossID>',views.bossProductDetailPage),
    path('boss/updateImage/<int:productID>/<int:imgID>', views.updateImg),
    path('boss/deleteImage/<int:productID>/<int:imgID>', views.deleteImg),
    path('boss/updateProduct/<int:productID>', views.updateProduct),
    path('boss/updateQuantity/<int:productID>/<int:detailID>', views.updateQuantity),
    path('boss/addSize/<int:productID>', views.addSize),
    path('boss/deleteProduct/<int:productID>/<int:bossID>', views.deleteProduct),
    path('boss/editAccountPage/<int:bossID>', views.editBossAccountPage),
    path('boss/deleteSize/<int:sizeID>', views.deleteSize),
    path('boss/updateAccount/<int:bossID>', views.updateBossAccount),
    path('boss/webadmin/<int:bossID>',views.webAdmin),
    path('add/service/<int:bossID>', views.addService),
    path('add/advert/<int:bossID>', views.addAdvert),
    path('delete/service/<int:serviceID>/<int:bossID>', views.deleteService),
    path('delete/ad/<int:adID>/<int:bossID>', views.deleteAd),
    path('payment/password/<int:bossID>', views.paymentSecurity),
    path('payment/security/create/<int:bossID>', views.createSecuriry),
    path('payment/security/edit/<int:bossID>', views.updateSecuriry),
    path('add/payment/<int:bossID>', views.addPayment),
    path('delete/payment/<int:payID>/<int:bossID>', views.deletePayment),
    path('boss/orders/<int:bossID>', views.bossOrderPage),
    path('searchOrder/<int:bossID>', views.searchOrder),
    path('searchOrder/pay/<int:bossID>', views.searchPay),
    path('searchOrder/ship/<int:bossID>', views.searchShip),
    path('boss/orderDetail/<int:orderID>/<int:bossID>', views.bossOrderDetail),
    path('boss/updateStatus/payment/<int:orderID>/<int:bossID>', views.updatePayStatus),
    path('boss/updateStatus/shipping/<int:orderID>/<int:bossID>', views.updateShipStatus),
    path('boss/report/<int:bossID>', views.reportPage),
    path('boss/order/delete/<int:orderID>/<int:bossID>', views.deleteOrder),

    path('userLogRegPage', views.userLogRegPage),
    path('userReg', views.userReg),
    path('userLog', views.userLog),
    path('userHome/<int:userID>', views.userHome),
    path('user/product/detail/<int:productID>/<int:userID>', views.userProductDetail),
    path('viewIMG/<int:productID>/<int:userID>/<int:imgID>',views.viewIMG),
    path('user/product/like/<int:productID>/<int:userID>', views.likeProduct),
    path('user/product/unlike/<int:productID>/<int:userID>', views.unlikeProduct),
    path('user/myfavorites/<int:userID>', views.myFavoritesPage),
    path('user/service/<int:userID>',views.servicePage),
    path('user/myaccount/<int:userID>', views.myAccount),
    path('user/account/update/<int:userID>', views.updateUserAccount),
    path('user/account/add/address/<int:userID>', views.addAddress),
    path('user/account/delete/address/<int:addressID>/<int:userID>', views.deleteAddress),
    path('user/shoppingPage/<int:productID>/<int:userID>', views.shoppingPage),
    path('user/shoppingcart/add/<int:userID>', views.addItemToCart),
    path('user/mycart/<int:userID>', views.myShoppingCart),
    path('user/shoppingcart/remove/<int:itemID>/<int:userID>', views.deleteItemFromCart),
    path('user/checkout/<int:userID>', views.checkoutPage),
    path('user/paying/<int:userID>', views.checkoutRedirect),
    path('user/payment/<int:userID>/<int:addressID>', views.payment),
    path('user/order/<int:userID>', views.generateOrder),
    path('user/orderInfo/<int:userID>', views.orderPage),
    path('user/orderDetail/<int:orderID>/<int:userID>', views.orderDetail),

    path('logout/<int:ID>',views.logout),
    # path('*',views.home)
]