# Generated by Django 2.1.3 on 2018-12-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20181219_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productInCate', to='ecommerce.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productInDetail', to='ecommerce.Product'),
            preserve_default=False,
        ),
    ]
