# Generated by Django 2.1.3 on 2018-12-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20181220_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoryInDetail', to='ecommerce.ProductCategory'),
            preserve_default=False,
        ),
    ]
