# Generated by Django 2.1.3 on 2018-12-23 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_advertisement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='User',
            new_name='user',
        ),
    ]
