# Generated by Django 2.1.3 on 2018-12-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20181224_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='zipcode',
            field=models.CharField(max_length=50),
        ),
    ]
