# Generated by Django 2.1.3 on 2018-12-25 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20181225_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inCartItem', to='ecommerce.ProductDetail'),
        ),
    ]
