# Generated by Django 2.1.3 on 2018-12-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20181226_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingCustomer', to='ecommerce.User'),
        ),
    ]
