# Generated by Django 2.1.3 on 2018-12-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_auto_20181228_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='buyerPhone',
        ),
    ]
