# Generated by Django 2.1.3 on 2018-12-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_auto_20181228_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='paymentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
